### PR TITLE
golang.org/x/tools/astutil was moved to golang.org/x/tools/go/ast/astutil

### PR DESCRIPTION
**Pull request by yuntan**
### Reference
* [[tools] astutil: move to go/astutil](https://groups.google.com/forum/#!topic/golang-codereviews/SHvYxM-5mzg)
* [astutil: move to go/ast/astutil](https://go-review.googlesource.com/#/c/2592/)

### CODE REVIEW

**Comment by bowmanb** [comment]
This resolved my build issues on Ubuntu w/ Go 1.4.1. Thanks.

**Comment by alinex** [comment]
Thanks for the fix, works for me, too.

**Comment by bep** [comment]
Worked for me, too.

**Comment by visualfc** [comment]
thanks

**Pull request closed without merging**
