### PR TITLE
Update Mac OS build instructions

### LINKED ISSUE #777: LiteIDE built with Qt5.5 crashes upon load
Qt5.5 was installed using brew
```
$ build/liteide/LiteIDE.app/Contents/MacOS/LiteIDE
2017-04-16 01:18:59.272 LiteIDE[67035:6622471] *** Assertion failure in -[NSBitmapImageRep initWithCGImage:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.81.100/AppKit.subproj/NSBitmapImageRep.m:1296
2017-04-16 01:18:59.276 LiteIDE[67035:6622471] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: cgImage != NULL'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff781c4e7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff8cda4cad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff781c9b82 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff79c13d50 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fff75dba112 -[NSBitmapImageRep initWithCGImage:] + 149
	5   QtGui                               0x0000000105328536 _Z21qt_mac_create_nsimageRK5QIconi + 694
	6   libqcocoa.dylib                     0x0000000107ebaa6d qt_plugin_instance + 149437
	7   libqcocoa.dylib                     0x0000000107eb7e07 qt_plugin_instance + 138071
	8   QtWidgets                           0x0000000104c586c9 _ZN5QMenu11actionEventEP12QActionEvent + 1369
	9   QtWidgets                           0x0000000104b20fdf _ZN7QWidget5eventEP6QEvent + 255
	10  QtWidgets                           0x0000000104c56361 _ZN5QMenu5eventEP6QEvent + 1169
	11  QtWidgets                           0x0000000104adff52 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 306
	12  QtWidgets                           0x0000000104ae12a8 _ZN12QApplication6notifyEP7QObjectP6QEvent + 360
	13  QtCore                              0x000000010573b93f _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 159
	14  QtWidgets                           0x0000000104b14abf _ZN7QWidget12insertActionEP7QActionS1_ + 351
	15  libliteapp.1.dylib                  0x000000010493ab65 _ZN7LiteApp11createMenusEv + 549
	16  libliteapp.1.dylib                  0x0000000104937d32 _ZN7LiteAppC2Ev + 4050
	17  libliteapp.1.dylib                  0x0000000104935995 _ZN7LiteApp14NewApplicationEbPN7LiteApi12IApplicationE + 37
	18  libliteapp.1.dylib                  0x00000001049322bc _Z12liteapp_mainiPPc + 4492
	19  libdyld.dylib                       0x00007fff8d688255 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

### PR DESCRIPTION
**Pull request by elfgoh**
Fix #777 with successful build on Qt 5.5

### CODE REVIEW

**Comment by visualfc** [comment]
please keep Qt4 build

**Comment by elfgoh** [comment]
Ok I will update this PR to include the build instructions for Qt4

**Comment by elfgoh** [comment]
Added back Qt 4 instructions

**Comment by visualfc** [comment]
fix Qt5.8 bug on macOS
https://github.com/visualfc/liteide/commit/d289ada95009a01106a540a221fb5a00431a4b03

**Comment by visualfc** [comment]
build and test pass for Qt5.7.1 on macOS

**Comment by elfgoh** [comment]
@visualfc did you install Qt from homebrew?

**Comment by visualfc** [comment]
http://www.qt.io/download 
qt-opensource-mac-x64-clang-5.7.1.dmg

**Comment by elfgoh** [comment]
I made this [commit](https://github.com/elfgoh/liteide/commit/b3a54784a4d54a7d639b3962e6109f563d1fb1f8t in my fork), in case you find it useful

**Comment by elfgoh** [comment]
I hope more developers can help to contribute if they can successfully build using Qt 5, because brew no longer as Qt4 for download. The instructions for Qt 5 hopes to help with that

**Comment by visualfc** [comment]
ok, thanks. please check and build on Qt5.7/Qt5.8, it run pass.

**Comment by elfgoh** [comment]
Build using Qt 5.8 installed from Homebrew fails:
`open liteide/LiteIDE.app/Contents/MacOS/LiteIDE`
```
$ /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/MacOS/LiteIDE ; exit;
objc[18509]: Class RunLoopModeTracker is implemented in both /usr/local/Cellar/qt/5.8.0_2/lib/QtCore.framework/Versions/5/QtCore (0x109170e40) and /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x108144e40). One of the two will be used. Which one is undefined.
objc[18509]: Class NotificationReceiver is implemented in both /usr/local/Cellar/qt/5.8.0_2/lib/QtWidgets.framework/Versions/5/QtWidgets (0x10869e0b0) and /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets (0x1076750b0). One of the two will be used. Which one is undefined.
objc[18509]: Class QCocoaPageLayoutDelegate is implemented in both /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x1071d9ed0) and /usr/local/Cellar/qt/5.8.0_2/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x109333ed0). One of the two will be used. Which one is undefined.
objc[18509]: Class QCocoaPrintPanelDelegate is implemented in both /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x1071d9f20) and /usr/local/Cellar/qt/5.8.0_2/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x109333f20). One of the two will be used. Which one is undefined.
QCoreApplication::arguments: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
Segmentation fault: 11
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]
```

**Comment by elfgoh** [comment]
Build using Qt 5.7 installed from Homebrew fails due to segfault:
open liteide/LiteIDE.app/Contents/MacOS/LiteIDE

```
$ /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/MacOS/LiteIDE ; exit;
objc[25081]: Class RunLoopModeTracker is implemented in both /usr/local/Cellar/qt@5.7/5.7.1/lib/QtCore.framework/Versions/5/QtCore (0x11167fdf0) and /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x1104cddf0). One of the two will be used. Which one is undefined.
objc[25081]: Class NotificationReceiver is implemented in both /usr/local/Cellar/qt@5.7/5.7.1/lib/QtWidgets.framework/Versions/5/QtWidgets (0x110ae3ef0) and /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets (0x10f92fef0). One of the two will be used. Which one is undefined.
objc[25081]: Class QCocoaPageLayoutDelegate is implemented in both /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x10f3e6eb0) and /usr/local/Cellar/qt@5.7/5.7.1/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x113aeaeb0). One of the two will be used. Which one is undefined.
objc[25081]: Class QCocoaPrintPanelDelegate is implemented in both /Users/plgl757e/Projects/go/src/github.com/visualfc/liteide/build/liteide/LiteIDE.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x10f3e6f00) and /usr/local/Cellar/qt@5.7/5.7.1/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x113aeaf00). One of the two will be used. Which one is undefined.
QCoreApplication::arguments: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
Segmentation fault: 11
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by elfgoh** [comment]
I am happy to try rebuilding using Qt 5.7 and 5.8 from `brew` if there are fixes pushed

**Comment by visualfc** [comment]
brew install qt@5.7
Brew may have bug and can compile but deploy errors (test sample same result)
please build only, but not use deploy_osx_qt5
$ build_osx_clang.sh
$ open liteide/LiteIDE.app

**Comment by visualfc** [comment]
qt.io install Qt5.6.2/Qt5.7.1/Qt5.8 can build and deploy
brew install Qt5.7 QT5.8 build only, run pass, but not deploy

**Comment by elfgoh** [comment]
Yay for qt@5.7
$ build_osx_clang.sh
$ open liteide/LiteIDE.app

Works successfully

**Comment by visualfc** [comment]
thanks

**Pull request merged**
